[tool.poetry]
name = "receipt-reader"
version = "0.2.0"
description = "Read Sainsbury's receipts and upload them to Google Sheets"
authors = ["Alexandra Whitham"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.21.0"
configparser = "^7.0.0"
argparse = "^1.4.0"
pdf2image = "^1.16.0"
google-cloud-vision = "^2.7.2"
google-api-python-client = "^2.11.0"
google-auth-oauthlib = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
